### PR TITLE
Set PYTHONPATH so that pylint can import stbt

### PR DESCRIPTION
**Pull request by drothlis**

### CODE REVIEW

**Comment by drothlis** [comment]
@wmanley: Please review.

**Comment by wmanley** [comment]
So this is for using `pylint` but without `stbt lint`?

**Comment by drothlis** [comment]
Yes, or ipython.

**Comment by drothlis** [comment]
I just noticed that one of the usage examples in the README uses python & `import stbt`, which doesn't actually work currently on master:

```
$ ./stbt-docker python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import stbt
>>> stbt.match(...)
```

**Comment by danielandersson** [comment]
@wmanley, @drothlis is there any reason why this haven't been merged yet?

**Comment by wmanley** [comment]
There is something that makes me nervous about this, but I can't quite put my finger on it.  I can definitely see that it would be useful and valuable though so +1

**Comment by drothlis** [comment]
I suppose the _correct_ solution would be to install stbt to the system PYTHONPATH (which we want to do anyway)... but that will require reading the Debian & Fedora Python packaging guidelines and figuring out how to do it properly. I'll merge this for now.

**Pull request merged**
